mod app;
mod appearance;
mod browser;
mod clipboard;
mod dbus;
mod ghostty_sys;
mod input;
mod install;
mod install_prompt;
mod notify;
mod port_detect;
mod remote;
mod session;
mod settings;
mod settings_ui;
mod sidebar;
mod socket;
mod split;
mod surface;
mod surfaces;
mod tab_strip;
mod tray;
mod update;
mod util;
mod window;
mod workspace;

use std::cell::RefCell;

use gtk4::prelude::*;
use gtk4::{self, gio, glib};

/// CLI options parsed from command line.
struct Options {
    working_directory: Option<String>,
    command: Option<String>,
    socket_path: Option<String>,
}

thread_local! {
    static WINDOW: RefCell<Option<gtk4::ApplicationWindow>> = const { RefCell::new(None) };
}

/// Called from action_cb to set the window title.
pub fn set_window_title(title: &str) {
    WINDOW.with(|w| {
        if let Some(window) = w.borrow().as_ref() {
            window.set_title(Some(title));
        }
    });
}

/// Called from close_surface_cb/action_cb to close the window.
pub fn close_window() {
    WINDOW.with(|w| {
        if let Some(window) = w.borrow().as_ref() {
            window.close();
        }
    });
}

/// AppImage runtime setup for WebKitGTK helper processes.
///
/// libwebkitgtk-6.0.so is byte-patched at AppImage build time to look
/// for the WebKit*Process helpers at /tmp/limux-webkit-helpers, and its
/// compiled-in injected-bundle path still points at the host system.
/// This recreates the /tmp sentinel symlink and exports the WebKit env
/// vars before GTK/WebKit initializes. It is a safety net for when the
/// AppRun launcher that normally does this is replaced (linuxdeploy's
/// autogenerated AppRun clobbers our custom one at seal time).
fn setup_appimage_webkit() {
    let Some(appdir) = std::env::var_os("APPDIR") else { return };
    let helper_dir = std::path::PathBuf::from(&appdir).join("usr/lib/webkitgtk-6.0");
    if helper_dir.is_dir() {
        let sentinel = std::path::Path::new("/tmp/limux-webkit-helpers");
        let ok = match std::fs::symlink_metadata(sentinel) {
            Ok(meta) => {
                meta.file_type().is_symlink()
                    && matches!(std::fs::read_link(sentinel), Ok(target) if target == helper_dir)
            }
            Err(_) => false,
        };
        if !ok {
            let _ = std::fs::remove_file(sentinel);
            let _ = std::os::unix::fs::symlink(&helper_dir, sentinel);
        }
    }
    // SAFETY: called from main() before any threads spawn, so the
    // process environment is not concurrently mutated.
    unsafe {
        std::env::set_var("WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS", "1");
        std::env::set_var("WEBKIT_DISABLE_DMABUF_RENDERER", "1");
        if helper_dir.is_dir() {
            std::env::set_var(
                "WEBKIT_INJECTED_BUNDLE_PATH",
                helper_dir.join("injected-bundle/libwebkitgtkinjectedbundle.so"),
            );
        }
        let lib_dir = std::path::PathBuf::from(&appdir).join("usr/lib");
        let ld = std::env::var("LD_LIBRARY_PATH").unwrap_or_default();
        if !ld
            .split(':')
            .any(|p| !p.is_empty() && std::path::Path::new(p) == lib_dir.as_path())
        {
            let value = if ld.is_empty() {
                lib_dir.to_string_lossy().into_owned()
            } else {
                format!("{}:{}", lib_dir.to_string_lossy(), ld)
            };
            std::env::set_var("LD_LIBRARY_PATH", value);
        }
    }
}

fn main() {
    setup_appimage_webkit();
    eprintln!("[limux-icon] creating app with application_id=com.limux.terminal");
    let app = gtk4::Application::new(
        Some("com.limux.terminal"),
        gio::ApplicationFlags::HANDLES_COMMAND_LINE
            | gio::ApplicationFlags::NON_UNIQUE,
    );
    // Register CLI options
    app.add_main_option(
        "working-directory",
        glib::Char::from(b'd'),
        glib::OptionFlags::NONE,
        glib::OptionArg::String,
        "Initial working directory",
        Some("DIR"),
    );
    app.add_main_option(
        "command",
        glib::Char::from(b'e'),
        glib::OptionFlags::NONE,
        glib::OptionArg::String,
        "Command to execute",
        Some("CMD"),
    );
    app.add_main_option(
        "socket",
        glib::Char::from(b's'),
        glib::OptionFlags::NONE,
        glib::OptionArg::String,
        "Socket path for CLI control",
        Some("PATH"),
    );

    // Parse options from command-line
    let options: std::rc::Rc<RefCell<Options>> = std::rc::Rc::new(RefCell::new(Options {
        working_directory: None,
        command: None,
        socket_path: None,
    }));

    let opts = options.clone();
    app.connect_command_line(move |app, cmdline| {
        let dict = cmdline.options_dict();
        {
            let mut o = opts.borrow_mut();
            o.working_directory = dict.lookup::<String>("working-directory").ok().flatten();
            o.command = dict.lookup::<String>("command").ok().flatten();
            o.socket_path = dict.lookup::<String>("socket").ok().flatten();
        } // drop borrow before activate
        app.activate();
        0
    });

    app.connect_startup(|_app| {
        eprintln!("[limux-icon] startup handler running (GTK now initialized)");
        gtk4::Window::set_default_icon_name("limux");
        eprintln!("[limux-icon] called gtk4::Window::set_default_icon_name(\"limux\")");
    });

    let opts = options.clone();
    app.connect_activate(move |app| {
        // Only activate once
        if app.active_window().is_some() {
            return;
        }

        // Initialize Ghostty backend
        if let Err(e) = crate::app::GhosttyApp::init() {
            eprintln!("Failed to initialize Ghostty: {e}");
            return;
        }

        let o = opts.borrow();

        // Load settings from disk
        settings::init();

        // Apply notification preference from settings
        if settings::get().notifications_enabled() {
            notify::enable();
        } else {
            notify::disable();
        }

        // Initialize color scheme detection before any CSS is loaded
        appearance::init();

        // Create the main window
        let gtk_window = gtk4::ApplicationWindow::builder()
            .application(app)
            .title("limux")
            .default_width(800)
            .default_height(600)
            .build();

        eprintln!(
            "[limux-icon] main window built, icon-name={:?}",
            gtk_window.icon_name()
        );

        // Probe whether the icon theme can find "limux"
        {
            let theme = gtk4::IconTheme::default();
            let icon_name = "limux";
            let has = theme.has_icon(icon_name);
            eprintln!(
                "[limux-icon] IconTheme::has_icon({}) = {}",
                icon_name, has
            );
            let paintable = theme.lookup_icon(
                icon_name,
                &[],
                256,
                1,
                gtk4::TextDirection::Ltr,
                gtk4::IconLookupFlags::PRELOAD,
            );
            let path = paintable
                .file()
                .and_then(|f| f.path())
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_else(|| "<no path>".to_string());
            let resolved_name = paintable
                .icon_name()
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_else(|| "<none>".to_string());
            eprintln!(
                "[limux-icon] IconTheme::lookup_icon({}) -> file={}, icon_name={:?}",
                icon_name, path, resolved_name
            );
        }

        // Track window focus for notification suppression
        gtk_window.connect_is_active_notify(move |win| {
            notify::set_window_active(win.is_active());
            tray::update_window_visible(win.is_active());
        });

        // Register notification click action: switch to a workspace by ID
        let switch_action = gio::SimpleAction::new("switch-workspace", Some(glib::VariantTy::UINT32));
        let win_for_action = gtk_window.clone();
        switch_action.connect_activate(move |_, param| {
            if let Some(ws_id) = param.and_then(|p| p.get::<u32>()) {
                window::select_workspace_by_id(ws_id);
                win_for_action.present();
            }
        });
        app.add_action(&switch_action);

        // Start socket server before creating terminals so shells inherit LIMUX_SOCKET
        socket::start(o.socket_path.as_deref());

        // Initialize the window with tab bar and first terminal
        window::init(
            &gtk_window,
            o.working_directory.as_deref(),
            o.command.as_deref(),
        );

        gtk_window.present();

        // Clone before gtk_window is moved into WINDOW
        let window_for_prompt = gtk_window.clone();

        WINDOW.with(|w| {
            *w.borrow_mut() = Some(gtk_window);
        });

        // First-run desktop integration prompt (AppImage only)
        install_prompt::maybe_show(&window_for_prompt);

        // Update check, delayed so it never stacks with the first-run prompt.
        let window_for_update = window_for_prompt.clone();
        glib::timeout_add_local_once(std::time::Duration::from_secs(4), move || {
            update::maybe_check(&window_for_update);
        });

        // Start system tray and D-Bus service
        tray::start();
        dbus::start();

        // Autosave session every 30 seconds
        session::start_autosave();

        // Poll for listening ports every 5 seconds
        window::start_port_polling();
    });

    app.connect_shutdown(|_app| {
        session::save_current_session();
        dbus::stop();
        tray::stop();
        socket::stop();
        crate::app::GhosttyApp::destroy();
    });

    let args: Vec<String> = std::env::args().collect();
    app.run_with_args(&args);
}
